### ISSUE TITLE
Promote search results based on full query string and article title

### ISSUE THREAD

**Issue by tmattia** [doximity/orientation#55]
When searching for queries that match article titles like "Network Update Email", the top result should be the article with that exact same title.

Example: https://www.dropbox.com/s/e864w1siem897gs/Screenshot%202017-05-03%2009.45.03.png?dl=0

**Comment by brupm** [comment]
This is working as expected, closing, please re-open if needed.
<img width="852" alt="screen shot 2017-08-21 at 12 28 58 pm" src="https://user-images.githubusercontent.com/336/29534834-5feb7dba-866c-11e7-962c-b08054de486b.png">
