### ISSUE TITLE
Add a bookmarks feature

### ISSUE THREAD

**Issue by nicholaspufal** [doximity/orientation#58]
I think someone else already mentioned this during retro. It would be awesome to be able to bookmark/pin articles that are relevant to ourselves. We do have a subscribe feature but that's a bit different - it isn't about knowing about updates but related to a quicker/easier access.

**Comment by brupm** [comment]
You can do this via the subscribe feature, then under your [profile](https://wiki.doximity.com/authors/206) you can see a list of subscriptions

**Comment by brupm** [comment]
I am not sure I want to add that complexity to the wiki seeing as we already have the subscription. Alternatively, you can bookmark using the browser. Please reopen if you feel passionate about it.
